Authentication microservice
AMT-2021/AMT pull request #89
Opened 2022-01-15 16:52 UTC by PaulReeve717

PR for our custom Authentication microservice

2022-01-15 17:24 UTC, roosemberth requested changes
I've left some small comments, but overall looks good, great work!

2022-01-15 17:24 UTC, roosemberth commented on ochap-authentication/src/main/java/com/example/ochapauthentication/entities/User.java
> +@Table(name = "user_table")
```suggestion
@Table(name = "users")
```

2022-01-15 17:24 UTC, roosemberth commented on ochap-authentication/src/main/java/com/example/ochapauthentication/entities/User.java
> +    private byte[] password;
This is not storing the password, but rather the hash of the password.

```suggestion
    private byte[] passwordHash;
```

2022-01-15 17:24 UTC, roosemberth commented on ochap-authentication/src/main/java/com/example/ochapauthentication/jwt/JwtTokenUtil.java
> +    private String doGenerateToken(Map<String, Object> claims, String subject) {
```suggestion
    private String generateJwtWithClaims(String subject, Map<String, Object> claims) {
```

Nitpick: Claims are associated to the subject, thus it is more intuitive to specify the subject first.

2022-01-15 17:24 UTC, roosemberth commented on ochap-authentication/src/main/java/com/example/ochapauthentication/routes/AuthenticationController.java
> +    ResponseEntity<String> loginAutentication(@RequestBody AuthLoginCommand credentials) throws JsonProcessingException {
```suggestion
    ResponseEntity<Object> loginAutentication(@RequestBody AuthLoginCommand credentials) throws JsonProcessingException {
```

Why not let spring to the marshalling for you?

2022-01-15 17:24 UTC, roosemberth commented on ochap-authentication/src/main/java/com/example/ochapauthentication/routes/AuthenticationController.java
> +    ResponseEntity<String> registerAutentication(@RequestBody AccountRegisterCommand credentials) throws JsonProcessingException {
```suggestion
    ResponseEntity<String> registerAutentication(@RequestBody AccountRegisterCommand credentials) throws JsonProcessingException {
```

Why not let spring to the marshalling for you?

2022-01-15 17:24 UTC, roosemberth commented on ochap-authentication/src/main/java/com/example/ochapauthentication/routes/AuthenticationController.java
> +            new com.example.ochapauthentication.dto.Error("The username already exist");
```suggestion
            new com.example.ochapauthentication.dto.Error("A user with the specified username already exists.");
```

The username identifies a user, but is not an entity on its own.

2022-01-15 17:24 UTC, roosemberth commented on ochap-authentication/pom.xml
> +            </plugin>
Missing formatter plugin:

```suggestion
            </plugin>
			<plugin>
				<groupId>net.revelc.code.formatter</groupId>
				<artifactId>formatter-maven-plugin</artifactId>
				<version>2.16.0</version>
				<configuration>
					<configFile>${project.basedir}/../eclipse-java-google-style.xml</configFile>
				</configuration>
			</plugin>
```

2022-01-15 17:24 UTC, roosemberth commented on ochap-authentication/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This module should be added to the parent pom aswell.

2022-01-15 17:24 UTC, roosemberth commented on ochap-authentication/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This module is missing a README.

2022-01-16 11:43 UTC, Klab93 commented on ochap-authentication/src/main/java/com/example/ochapauthentication/dto/Error.java
> +public class Error {
AuhtenticationController line 60

2022-01-16 16:25 UTC, roosemberth requested changes
Almost there, just a little update on the README!

2022-01-16 16:25 UTC, roosemberth commented on ochap-authentication/README.md
> +```
This section is outdated.

2022-01-16 16:39 UTC, roosemberth approved these changes
Amazing! Thanks for your contribution!

2022-01-16 16:45 UTC, merged